# Generated by Django 4.2.4 on 2023-08-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.IntegerField(
                        choices=[(1, "นาย"), (2, "นาง"), (3, "นางสาว")]
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={"verbose_name": "Author", "verbose_name_plural": "Authors",},
        ),
    ]
